# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/xmk

name: 'Build native_posix_64 board'
#on: [push, pull_request, workflow_dispatch]
on: [pull_request, workflow_dispatch]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: zmk-config
      build_matrix_path: zmk-config/native_posix_64.yml
      fallback_binary: elf
      archive_name: xmk-native_posix_64-board
